theme: jekyll-theme-minimal
logo: /img/ensta-couleur.jpg
description: Projet éducatif visant à évaluer l'implémentation d'un processeur d'architecture RISC-V sur un FPGA en utilisant les outils de conception Migen et LiteX.
show_downloads: true
title: LiteX - Le framework open-source pour programmer du matériel en Python