theme: jekyll-theme-minimal
logo: /img/ensta-couleur.jpg
description: Projet éducatif visant à évaluer l'implémentation d'un processeur d'architecture RISC-V sur un FPGA en utilisant les outils de conception Migen et LiteX. Contributeurs originaux https://github.com/SylvainEnsta et https://github.com/durandau
show_downloads: true
title: RISC-V PoC with LiteX